### ISSUE TITLE
The performance of `first` and `last` can be improved

### ISSUE THREAD

**Issue by nfgrusk** [paluh/purescript-pointed-list#4]
The current implementation of `first` is more or less equivalent to the following:

```purescript
first ∷ ∀ a. Pointed a → Pointed a
first (Pointed { focus, reversedPrefix, suffix }) = Pointed
    { focus: unsafePartial (Partial.head intermediateResult2)
    , reversedPrefix: Nil
    , suffix: unsafePartial (Partial.tail intermediateResult2)
    }
  where
    intermediateResult1 = reverse (Cons focus reversedPrefix)
    --                    ☝︎ foldl (flip Cons) Nil (Cons focus reversedPrefix)
    intermediateResult2 = intermediateResult1 <> suffix
    --                    ☝︎ foldr Cons suffix intermediateResult1
```

  * Eliminating one of the two fold operations is one way of improving the performance of `first`.

    The expression `foldr Cons suffix <<< foldl (flip Cons) Nil` can be simplified to just `foldl (flip Cons) suffix`. Thus, we get `intermediateResult2 = foldl (flip Cons) suffix $ Cons focus reversedPrefix`.

  * There’s another way of improving the performance of `first` and it is *muuuuch* easier to understand. 😄

    ```purescript
    first ∷ ∀ a. Pointed a → Pointed a
    first p = case prev p of
      Just p' → first p'
      Nothing → p
    ```

    This is about as fast as using a single fold operation because the tail-call optimization phase of the compiler translates the recursive definition into a while loop.

Both ideas can also be applied to the implementation of `last` (by swapping `suffix` and `reservedPrefix` and by replacing `prev` with `next`, respectively).

**Comment by paluh** [comment]
@ewaldgrusk Sorry for late response. I've missed your commit and comment. Please let me read through it and merge these changes hopefully tomorrow or day after as I'm really busy before this weekend...

**Comment by nfgrusk** [comment]
It’s fine. Don’t worry about it. 😄

**Comment by paluh** [comment]
To be honest it wasn't hard read so I'm merging it now :-)

**Comment by paluh** [comment]
I'm not sure why I thought that direct usage of `prev` or `next` would decrease performance... :-)

New release is on the way. Thanks a lot!
