### ISSUE TITLE
Include space-prioritized pointed list?

### ISSUE THREAD

**Issue by JordanMartinez** [paluh/purescript-pointed-list#6]
This library's current approach to an undo/redo manager prioritizes time over space. In other words, if my `a` element in `Pointed a` stored a massive amount of data and I want to undo/redo something in that data that only changes one thing, I would be duplicating a lot of data unnecessarily.

Another way this idea could be implemented is via a [change object](https://gist.github.com/JordanMartinez/9e558dff223ebc6c40943b3fa4655b78#file-second-purs). This approach would prioritize space over time.

I'm not familiar with the Haskell version of `pointed-list`, but since this library is a port of that library, should this idea be included in this repo based on the similarity for how to handle undos/redos? Or should it be turned into its own separate repo?

**Comment by paluh** [comment]
Hi @JordanMartinez,

Thanks for your propostion and intreset in this lib ;-)
I'm not sure if I understand fully your exact scenario but I think we have something similar in our app - we don't keep snapshots of the whole state anymore and use "reversabe" history entries.
In history we keep representation of change and interpreting it later. So we have `Group`  instance for our history entries:

```purescript
instance groupEntry ∷ Group Entry where
  ginverse (Add arr) = Remove arr
  ginverse (ChangeColor {id, from, to}) = ChangeColor {id, from: to, to: from}
  ginverse (ChangeLevel { id, direction: Up }) = ChangeLevel { id, direction: Down }
  ginverse (ChangeOpacity {id, from, to}) = ChangeOpacity {id, from: to, to: from}
  ginverse (Move { id, trans:(Vector {x, y})}) = Move {id, trans: (Vector {x: -x, y: -y})}

  ...
```

and we have some interpreter - something like:

```purescript
execute ∷ Entry → Scene → Scene
```

It works pretty well ;-)


As a side note - we are separating actions on the scene from entries in history. We encapsulate our scene in like `Machine` abstraction which gets `Action` and turns them into history entries - which are interpreted (so we have like two layers but quite nice separation):

```purescript
data Modification
  = Move Vector
  | Rotate Radians
  | Scale Number
  | SetColor Color
  | SetOpacity Number
  ...

data Action
  = Add (Array Figure)
  | History Direction
  | ModifyObject
      { id ∷ ID
      , modification ∷ Modification
      }
  | Remove (Array ID)
```


Our API to the scene is a Machine build on top of this simple stepper which turns `Action` into `Entry` (adds it to history if it is not an history action) and interprets it:

```purescript
stepper ∷ Scene → Action → m (Step m Action Scene)
```

**Comment by paluh** [comment]
P.S.
So `undo` is "like" (pseudo code!): `prev >>> ginverse >>> execute` and `redo` dosn't use `ginverse`.

**Comment by paluh** [comment]
P.S. 
There are some dirty edges of our API for example "dragging"  scenario when changes are not applied directly during the dragging to our scene but at the end of the move we emit execute `step` with final `Action` containing translation for the whole move but I think i is not important here.

**Comment by JordanMartinez** [comment]
Basically, my 'exact scenario' is to port over [FXMisc/RichTextFX](https://github.com/FXMisc/RichTextFX/) via Halogen, which uses [FXMisc/UndoFX](https://github.com/FXMisc/UndoFX) as its undo manager.

Thus, the state I am storing is the content of the document that may contain a huge number of "paragraphs". While it can (and will) be more complicated than this, for simplicity's sake, consider these paragraphs as nothing more than a `String`. An undo could be as simple as inserting/deleting/replacing one letter in that document; hence, I don't want to store the entire document in each part of the `PointedList`. 

Also, there are times when the changes should be "merged". By inserting "a" (user pressed the 'a' key) and then inserting "b" (user pressed the 'b' key immediately after), I can store one change that inserts "ab". When the user undos the change, the "ab" part is deleted instead of just the 'b'.

**Comment by paluh** [comment]
I'm not sure if I'm able to model it in a sane way right away but you can have history `Entry` like:

```purescript
data Entry = Insert Location String | Delete Location String
```

Regarding actions "compression" you can provide some merging strategy (or even a `Monoid` instance) and when you are just above to add an action you can check current focus if it meets your requirements for merging with this new `Entry` you can merge and `replace` if not you can go and add new `Entry` to history.
 
Am I missing something in this simple approach?

**Comment by paluh** [comment]
Of course there is some redundancy in for example `Delete` entry as we keep the content of deleted `String` so we are able to `ginverse` it and have `Insert` from it.

**Comment by JordanMartinez** [comment]
I'm not sure. Still, I think for now, I'll just port the FXMisc/Undo library the way it is and then improve the API later in some breaking change. Right now, my goal is just to figure out what problems I need to handle due to how browsers work. Once these problems have been identified, I can then refine the solution.

My original question for opening this issue can be rephrased like so: is this library strictly a port of Haskell's `pointed-list`? If so, then any modifications to this idea should not be stored here but included in a repo that depends on this repo, so that people can share the same `PointedList` type. If not, then any modifications to this idea (in terms of adding other API for domains that use a pointed list) could be included here.

**Comment by paluh** [comment]
It is really close port of Haskell library. But I'm not able to understand what does it mean "time prioritized" and I want to know this. I don't think that moving API to `typeclass` level changes anything. In your api you are doing interpretation through typeclass method and implementing `ginverse` with this `Invertable`...
I really don't get it where it is this space prioritizatoin.

**Comment by paluh** [comment]
Of course the other completely different question is how you are going to store your document so it won't be whole copied on every change. But I think that this is completely different story..

**Comment by JordanMartinez** [comment]
I re-read through this issue and things make more sense now. In your example above, you have a `Group` instance, but I did not understand what that was when I first read through it. After looking it up, now I understand what it is. Originally, I speed-read your explanation but didn't understand it, so I decided just to explain what my goal was and continue the conversation there.

Now that I understand what `Group` means and having reread your original example at a slower pace, I now understand what you are doing and that does seem like it will work for my use case.

**Comment by paluh** [comment]
@JordanMartinez To be honest there is not much in this library. It is only a nonempty list with selected element :-)

**Comment by JordanMartinez** [comment]
Right, but it can be used to build higher abstractions. Your above example shows one such "pattern" that works as an undo manager and is a pattern I can re-use in my code.

Now that I understand your example better, I don't think there is a need to add something to this library. Rather, perhaps the 'pattern' could be abstracted into a new project.

**Comment by paluh** [comment]
@JordanMartinez 
The only problem with implementation of `inverse` using `Group` is that `Group` requires an `Monoid` which is not always what we want in such a case I wolud provide just `inverse` on its own without any typeclass.
